name: AuctionHouse
author: VMPE Development Team
main: semteul\directauction\DirectAuction
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
version: "1.0-BETA"
permissions:
  auctionhouse:
    description: "Auction house command"
    aliases: ["ah"]
    default: true
